### ISSUE TITLE
qca-nss-ecm comiplation error on ipq60xx-6.6

### ISSUE THREAD

**Issue by 67113513** [breeze303/openwrt-ipq60xx#1]
### Describe the bug

./feeds/nss_packages/qca/qca-nss-ecm/patches/0001-treewide-componentize-the-module-even-more.patch needs to be ported to 6.6. 
![图片](https://github.com/breeze303/ipq60xx-6.6/assets/17248154/f2ccac8d-a591-41e0-9b99-619f047f7a60)

### OpenWrt version

compilation error on main branch

### OpenWrt release

compilation error on main branch

### OpenWrt target/subtarget

IPQ60xx

### Device

Multiple devices

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by 67113513** [comment]
on new cloned code, and choose the menu:
![图片](https://github.com/breeze303/ipq60xx-6.6/assets/17248154/02050989-fa2a-431c-b9ed-cf5ca00afd9c)

**Comment by 67113513** [comment]
By default, no ecm.ko generated:
![图片](https://github.com/breeze303/ipq60xx-6.6/assets/17248154/2bf9d3ff-2072-4044-9054-d75998942e25)

**Comment by 67113513** [comment]
And then I changed 0001-treewide-componentize-the-module-even-more.patch manually, set findstring to 6.6, and got some other errors:
![图片](https://github.com/breeze303/ipq60xx-6.6/assets/17248154/fbe17f9d-1a21-42f3-8ac4-196cc46313e5)

**Comment by breeze303** [comment]
You can refer to this library to fix it, I don't have time to fix it lately
https://github.com/qosmio/nss-packages

**Comment by 67113513** [comment]
new nss feed works

**Comment by breeze303** [comment]
Solved?

**Comment by 67113513** [comment]
replaced nss feed and add following line to config:
CONFIG_PACKAGE_kmod-qca-nss-ecm=y
then the compilation passed, but haven't done the test yet.

**Comment by Canary233** [comment]
> replaced nss feed and add following line to config: CONFIG_PACKAGE_kmod-qca-nss-ecm=y then the compilation passed, but haven't done the test yet.

Can you turn on Wlan when you're using https://github.com/qosmio/nss-packages?
